[package]
name = "aivi-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aivi-ffi-call = { path = "../aivi-ffi-call" }
aivi-base.workspace = true
aivi-core = { path = "../aivi-core" }
aivi-hir.workspace = true
aivi-lambda.workspace = true
aivi-typing.workspace = true
postcard.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-native.workspace = true
cranelift-object.workspace = true
indexmap = { version = "2", features = ["serde"] }
num-bigint = { version = "0.4.6", features = ["serde"] }
num-traits = "0.2"
rayon = "1"
rust_decimal = { version = "1.40.0", features = ["serde"] }
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
aivi-query.workspace = true
aivi-syntax.workspace = true

[lints.rust]
unsafe_code = "deny"
